[package]
name = "tuirealm"
version = "0.1.0"
authors = ["Christian Visintin"]
edition = "2018"
categories = ["command-line-utilities"]
description = "A tui-rs framework to build interfaces, inspired by React and Elm."
documentation = "https://docs.rs/tuirealm"
homepage = "https://github.com/veeso/tui-realm"
include = ["docs/", "src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["tui", "terminal"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/veeso/tui-realm"

[dependencies]
tui = { version = "0.14.0", default-features = false, features = ["crossterm"] }
crossterm = { version = "0.19" }
textwrap = { version = "0.13.4", optional = true }
unicode-width = { version = "0.1.8", optional = true }

[features]
with-components = [ "textwrap", "unicode-width" ]

[[example]]
name = "gallery"
path = "examples/gallery.rs"
required-features = [ "with-components" ]
