[package]
name = "tuirealm"
version = "0.5.1"
authors = ["Christian Visintin"]
edition = "2018"
categories = ["command-line-utilities"]
description = "A tui-rs framework to build interfaces, inspired by React and Elm."
documentation = "https://docs.rs/tuirealm"
homepage = "https://github.com/veeso/tui-realm"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["tui", "terminal"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/veeso/tui-realm"

[dependencies]
tui = { version = "0.15.0", default-features = false, features = ["crossterm"] }
crossterm = { version = "0.19" }

[dev-dependencies]
pretty_assertions = "0.7.2"
rand = "0.8.4"

[[example]]
name = "demo"
path = "examples/demo.rs"
